### ISSUE TITLE
Storing session for longer term use

### ISSUE THREAD

**Issue by adregan** [kra3/py-ga-mob#18]
Is there a way to store the utmb (in mongo, for example) so that we could use it on subsequent requests using the `extract_from_utmb` method?

**Comment by kra3** [comment]
If you want to re-use session then better way will be serializing the session object itself.
Instead if you store utmp cookie and use it to update a new ```Session``` object using ```extract_from_utmb``` it might not work, because now session object has a new id (that means a new session).

Sorry for delay :disappointed:
