### ISSUE TITLE
Please consider adding support for Batch requests.

### ISSUE THREAD

**Issue by bilalba** [kra3/py-ga-mob#26]
Batch requests allows batching upto 20 requests. This can reduce the number of requests that the application has to make 20 folds.

Here is more on batch requests: [https://developers.google.com/analytics/devguides/collection/protocol/v1/devguide#batch](https://developers.google.com/analytics/devguides/collection/protocol/v1/devguide#batch)

**Comment by kra3** [comment]
sure, why not.

**Comment by eltismerino** [comment]
+1!

**Comment by kra3** [comment]
Since `ga.js` is deprecated new features won't be added to the this lib, but efforts will be concentrated on a new version based against google's new measurement protocol.
