### ISSUE TITLE
Are custom dimensions supported?

### ISSUE THREAD

**Issue by reece** [kra3/py-ga-mob#31]
UA (and perhaps GA) provides "Custom Dimensions". Are these possible to use with pyga?

https://developers.google.com/analytics/devguides/collection/analyticsjs/custom-dims-mets

**Comment by kra3** [comment]
Hello @reece, this library is written against `GA.js`, while I have plans to create a version for `UA`, time is not in favour so far. 

That said, `pyga` has supports for `custom variables`, `events` & `campaigns` from `ga.js`. Most likely, one of those will work for you.

For example, ga.js variables can be thought of us less capable version of analytics.js dimensions.
https://github.com/kra3/py-ga-mob/blob/93fb6576ca57eca85d5bb5e1b17e74c99f8559a0/pyga/entities.py#L130-L171
