### ISSUE TITLE
Ad-Words / Search Engine support

### ISSUE THREAD

**Issue by isantolin** [kra3/py-ga-mob#32]
the Adwords or Search Engine features are already implemented (Partially at least)? @kra3 What has been planned?

**Comment by kra3** [comment]
`Adwords` and `Search Engine` features in `ga.js` is through `Campaigns`.

https://github.com/kra3/py-ga-mob/blob/61f5c2f3b4e1a4aea42afbf1a0c7df5a1f242b86/pyga/entities.py#L19-L45

Internals are (how the Campaign objects gets translated later is shown below

https://github.com/kra3/py-ga-mob/blob/5adfa1e55246e1c1b9b6b80805ad99f9cf8768fe/pyga/requests.py#L722-L736

However you may want to explore `anayalytics.js` or `gtags.js`. I am working on a version based on those, but don't have an expected release date.

**Comment by isantolin** [comment]
@kra3 Thanks.
Can you add an example to https://github.com/kra3/py-ga-mob/blob/master/README.rst File?
